[module.hugoVersion]
min = "0.158.0"

[[module.imports]]
path = "github.com/hugomods/utterances"

[markup.highlight]
noClasses = false

[params.utterances]
mapping = "pathname"
label = ""
theme = "preferred-color-scheme"

[[module.imports]]
path = "github.com/hugomods/mermaid"

[[module.imports]]
path = "github.com/hugomods/katex"

[params.mermaid]
js_url = "https://cdn.jsdelivr.net/npm/mermaid@11.12.0/dist/mermaid.esm.min.mjs"

[params.rainbow]
monoFontCSS = "https://cdn.jsdelivr.net/npm/@fontsource/maple-mono@5.3.0/index.min.css"
readingFontCSS = "https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.7.0/style.min.css"

[params]
CodeHighlighter = "chroma"
