# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "RainBow"
license = "MIT"
licenselink = "https://github.com/czyt/hugo-RainBow/blob/master/LICENSE"
description = "A reading-focused Hugo theme with side TOC, image zoom and GitHub issue comments"
homepage = "https://github.com/czyt/hugo-RainBow"
tags = [
  "responsive",
  "blog",
  "clean",
  "minimal",
  "light",
  "dark",
  "fast",
  "multilingual",
  "search",
  "seo",
  "chroma",
  "personal"
]
features = [
  "responsive",
  "single-column",
  "blog",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "twitter-cards",
  "favicon",
  "archive",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search",
  "breadcrumbs",
  "reading-time",
  "word-count",
  "code-copy",
  "comments",
  "edit-post",
  "canonical-link",
  "profile-mode",
  "home-info-mode",
  "related-posts",
  "rss",
  "multiple-authors",
  "post-nav-links"
]
min_version = "0.158.0"

[author]
  name = "czyt"
  homepage = "https://github.com/czyt/"

[original]
  name = "PaperMod"
  author = "Aditya Telange"
  homepage = "https://github.com/adityatelange/"
  repo = "https://github.com/adityatelange/hugo-PaperMod/"
