blank_issues_enabled: false
contact_links:
  - name: RainBow Discussions
    url: https://github.com/czyt/hugo-RainBow/discussions
    about: Please ask and answer questions/doubts here, DO NOT open an issue for questions.
