name: Enhancement 🚀
description: Propose a new feature or change for enhancing the experience.
title: "[Enhancement]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Describe the use case and the expected behavior in RainBow.
        Documentation: [RainBow README](https://github.com/czyt/hugo-RainBow#readme).
        - Use [Discussions](https://github.com/czyt/hugo-RainBow/discussions) section if you have a query or doubts or any other relevant question.
        - Search for previous [Issues](https://github.com/czyt/hugo-RainBow/issues)/[Pull Requests](https://github.com/czyt/hugo-RainBow/pulls) if this issue is already reported or fix has been created.
  - type: textarea
    id: what_happened
    attributes:
      label: What you'd like to propose?
      description:
      placeholder:
    validations:
      required: true
  - type: checkboxes
    id: checked_docs
    attributes:
      label: Before submitting
      options:
        - label: I checked the RainBow README and existing issues.
          required: true
